const PRIZES=[{label:'5% Reducere',code:'WOW5',color:'#1a0505',tc:'#e31e24',w:30},{label:'10% Reducere',code:'WOW10',color:'#e31e24',tc:'#fff',w:25},{label:'Mai mult noroc',code:null,color:'#111',tc:'#444',w:20},{label:'15% Reducere',code:'WOW15',color:'#b01419',tc:'#fff',w:15},{label:'5% Reducere',code:'WOW5',color:'#1a0505',tc:'#e31e24',w:30},{label:'Transport Gratuit',code:'FREESHIP',color:'#e31e24',tc:'#fff',w:10},{label:'20% Reducere',code:'WOW20',color:'#7a0d11',tc:'#fff',w:8},{label:'10% Reducere',code:'WOW10',color:'#b01419',tc:'#fff',w:25}];
let _canvas,_ctx,_angle=0,_spinning=false,_animId;
function initSpinCanvas(){_canvas=document.getElementById('spinCanvas');if(!_canvas)return;_ctx=_canvas.getContext('2d');drawWheel(_angle);}
function drawWheel(a){if(!_canvas||!_ctx)return;const cx=_canvas.width/2,cy=_canvas.height/2,r=cx-4,sl=(2*Math.PI)/PRIZES.length;_ctx.clearRect(0,0,_canvas.width,_canvas.height);PRIZES.forEach((p,i)=>{const s=a+i*sl,e=s+sl,m=s+sl/2;_ctx.beginPath();_ctx.moveTo(cx,cy);_ctx.arc(cx,cy,r,s,e);_ctx.closePath();_ctx.fillStyle=p.color;_ctx.fill();_ctx.strokeStyle='rgba(255,255,255,.08)';_ctx.lineWidth=1.5;_ctx.stroke();_ctx.save();_ctx.translate(cx,cy);_ctx.rotate(m);_ctx.textAlign='right';_ctx.fillStyle=p.tc;_ctx.font=`bold 11px Montserrat,sans-serif`;_ctx.shadowColor='rgba(0,0,0,.5)';_ctx.shadowBlur=4;_ctx.fillText(p.label,r-12,5);_ctx.restore();});const cg=_ctx.createRadialGradient(cx,cy,0,cx,cy,26);cg.addColorStop(0,'#e31e24');cg.addColorStop(1,'#7a0d11');_ctx.beginPath();_ctx.arc(cx,cy,26,0,Math.PI*2);_ctx.fillStyle=cg;_ctx.fill();_ctx.fillStyle='#fff';_ctx.font='bold 14px sans-serif';_ctx.textAlign='center';_ctx.textBaseline='middle';_ctx.fillText('🎰',cx,cy);}
function getWinIdx(){const t=PRIZES.reduce((s,p)=>s+p.w,0);let r=Math.random()*t;for(let i=0;i<PRIZES.length;i++){r-=PRIZES[i].w;if(r<=0)return i;}return PRIZES.length-1;}
function spinWheel(){if(_spinning)return;_spinning=true;const wi=getWinIdx(),sl=(2*Math.PI)/PRIZES.length,ta=(2*Math.PI*8)+(Math.PI*2-(wi*sl+sl/2)),sa=_angle,dur=5000,st=performance.now();document.getElementById('spin-btn')?.setAttribute('disabled','true');function ease(t){return 1-Math.pow(1-t,4);}function frame(now){const el=now-st,pr=Math.min(el/dur,1);_angle=sa+ta*ease(pr);drawWheel(_angle);if(pr<1){_animId=requestAnimationFrame(frame);}else{_spinning=false;showSpinPrize(PRIZES[wi]);}}requestAnimationFrame(frame);}
function showSpinPrize(p){const r=document.getElementById('spin-result'),pt=document.getElementById('spin-prize'),pc=document.getElementById('spin-code'),btn=document.getElementById('spin-btn');if(btn)btn.style.display='none';if(r)r.classList.add('show');if(!p.code){if(pt)pt.textContent='Mai mult noroc data viitoare! 🍀';if(pc)pc.style.display='none';return;}if(pt)pt.textContent=`🎉 Ai câștigat ${p.label}!`;if(pc){pc.textContent=p.code;pc.style.display='';}localStorage.setItem('discount_code',p.code);}
function spinHandleEmail(e){e.preventDefault();const form=e.target;form.style.display='none';const btn=document.getElementById('spin-btn');if(btn){btn.style.display='flex';btn.removeAttribute('disabled');}cartShowToast('Email înregistrat! Acum rotește roata! 🎉');}
window.spinWheel=spinWheel;window.spinHandleEmail=spinHandleEmail;window.initSpinCanvas=initSpinCanvas;
document.addEventListener('DOMContentLoaded',()=>{initSpinCanvas();});
